### ISSUE TITLE
Best way to I stall ffmpeg ?

### ISSUE THREAD

**Issue by gedw99** [mowshon/moviego#4]
Assume it’s not embedded.

man on Mac. Maybe you are also ?

**Comment by HGriessel** [comment]
I see they have a officail build on the site 

https://www.ffmpeg.org/download.html#build-mac

it would also seem that you can install via homebrew

https://phoenixnap.com/kb/ffmpeg-mac

Note: I did not test any of these methods

**Comment by gedw99** [comment]
Thanks

I built a tool to grab it for each OS.
